# Change these first
owner: linkspreed # Your GitHub organization or username, where this repository lives
repo: linkspreed_uptime # The name of this repository

sites:
  - name: Adseasy
    url: https://adseasy.linkspreed.com
  - name: Airr
    url: https://airr.linkspreed.com
  - name: Analytix
    url: https://analytix.linkspreed.com
  - name: Articly
    url: https://articly.linkspreed.com
  - name: Backpay
    url: https://backpay.cf
  - name: BeSave
    url: https://besave.linkspreed.com
  - name: BeYou
    url: https://beyou.linkspreed.com
  - name: Biospreed
    url: https://biospreed.linkspreed.com
  - name: BioX
    url: https://biox.linkspreed.com
  - name: Botchat
    url: https://botchat.linkspreed.com
  - name: CallCloud
    url: https://callcloud.linkspreed.com
  - name: Ceal
    url: https://ceal.linkspreed.com
  - name: Cheezz
    url: https://cheezz.linkspreed.com
  - name: Chirp
    url: https://chirp.linkspreed.com
  - name: Chitter
    url: https://chitter.linkspreed.com
  - name: Cloud2Go
    url: https://cloud2go.linkspreed.com
  - name: Cloud2Go Share
    url: http://share.cloud2go.tk
  - name: Cloud2Share
    url: https://cloud2share.linkspreed.com
  - name: CloudSpreed
    url: https://cloudspreed.linkspreed.com
  - name: Connected
    url: https://connected.linkspreed.com
  - name: Contribution
    url: https://contribution.linkspreed.com
  - name: Critch
    url: https://critch.linkspreed.com
  - name: CrossQA
    url: https://crossqa.linkspreed.com
  - name: Datify
    url: https://datify.linkspreed.com
  - name: DeePage
    url: https://deepage.linkspreed.com
  - name: Discounty
    url: https://discounty.tk
  - name: Diskit
    url: https://diskit.linkspreed.com
  - name: DNServer
    url: https://dnserver.linkspreed.com
  - name: Downflix
    url: https://downflix.linkspreed.com
  - name: Dreambuild
    url: https://dreambuild.linkspreed.com
  - name: Firelaps
    url: https://firelaps.cf
  - name: FlipX
    url: https://flipx.linkspreed.com
  - name: ForJu
    url: https://forju.linkspreed.com
  - name: GetPro
    url: https://getpro.linkspreed.com
  - name: Gogola
    url: https://gogola.linkspreed.com
  - name: Grown
    url: https://grown.linkspreed.com
  - name: Guju
    url: https://guju.linkspreed.com
  - name: Him4Her
    url: https://him4her.linkspreed.com
  - name: Hutty
    url: https://hutty.linkspreed.com
  - name: IceCloud
    url: https://icecloud.linkspreed.com
  - name: Ignyte
    url: https://ignyte.linkspreed.com
  - name: Joyn
    url: https://joyn.linkspreed.com
  - name: Kisk
    url: https://kisk.linkspreed.com
  - name: KitChat
    url: https://kitchat.linkspreed.com
  - name: LaaS
    url: https://laas.linkspreed.com
  - name: LaaS Chatbot
    url: https://chatbot.laas.ml
  - name: LaaS Cloudchat
    url: https://cloudchat.laas.ml
  - name: LaaS Salesy
    url: https://salesy.laas.ml
  - name: Shorts
    url: https://shorts.laas.ml
  - name: LaaS Tasks
    url: https://tasks.laas.ml
  - name: Lime
    url: https://lime.linkspreed.com
  - name: LinkCream
    url: https://linkcream.tk
  - name: Linkspreed
    url: https://linkspreed.com
  - name: Linkspreed AI
    url: https://ai.linkspreed.com
  - name: Linkspreed Assistant
    url: https://assistant.linkspreed.com
  - name: Linkspreed Analytics
    url: https://analytics.linkspreed.com
  - name: Linkspreed Drive
    url: https://drive.linkspreed.com
  - name: Linkspreed Helpdesk
    url: https://helpdesk.linkspreed.com
  - name: Linkspreed Research Lab
    url: https://lab.linkspreed.com
  - name: Linkspreed Mails
    url: https://mails.linkspreed.com
  - name: Linkspreed Office
    url: https://office.linkspreed.com
  - name: Linkspreed Panel
    url: https://panel.linkspreed.com
  - name: Linkspreed Photos
    url: https://photos.linkspreed.com
  - name: Linkspreed Play
    url: https://play.linkspreed.com
  - name: Linkspreed Search
    url: https://search.linkspreed.com
  - name: Linkspreed Store
    url: https://store.linkspreed.com
  - name: Linkspreed Web
    url: https://web.linkspreed.com
  - name: Linkspreed Web4
    url: https://web4.linkspreed.com
  - name: LinkLab
    url: https://linklab.linkspreed.com
  - name: LSily
    url: https://lsily.linkspreed.com
  - name: LSNews
    url: https://lsnews.linkspreed.com
  - name: Mailspread
    url: https://mailspread.linkspreed.com
  - name: Mapsli
    url: https://mapsli.linkspreed.com
  - name: Memevid
    url: https://memevid.linkspreed.com
  - name: Metabox
    url: https://metabox.linkspreed.com
  - name: Metaspace
    url: https://metaspace.linkspreed.com
  - name: Musiccloud
    url: https://musiccloud.linkspreed.com
  - name: MyBuy
    url: https://mybuy.linkspreed.com
  - name: MyDancX
    url: https://mydancx.linkspreed.com
  - name: Netavark
    url: https://netavark.linkspreed.com
  - name: NetSky
    url: https://netsky.linkspreed.com
  - name: NewsNode
    url: https://newsnode.linkspreed.com
  - name: Niming
    url: https://niming.linkspreed.com
  - name: Nither
    url: https://nither.linkspreed.com
  - name: NodX
    url: https://nodx.linkspreed.com
  - name: OnlyPaid
    url: https://onlypaid.linkspreed.com
  - name: Ondu
    url: https://ondu.linkspreed.com
  - name: Payback
    url: https://payback.ga
  - name: Payback
    url: https://payback.gq
  - name: PayCount
    url: https://paycount.linkspreed.com
  - name: Peek
    url: https://peek.linkspreed.com
  - name: Petabyte
    url: https://petabyte.linkspreed.com
  - name: PinPix
    url: https://pinpix.linkspreed.com
  - name: PinSec
    url: https://pinsec.linkspreed.com
  - name: Pixly
    url: https://pixly.linkspreed.com
  - name: Ples
    url: https://ples.linkspreed.com
  - name: Plop
    url: https://plop.linkspreed.com
  - name: Poddy
    url: https://poddy.linkspreed.com
  - name: Podhub
    url: https://podhub.linkspreed.com
  - name: Profilio
    url: https://profilio.linkspreed.com
  - name: Pubit
    url: https://pubit.tk
  - name: Qizz
    url: https://qizz.linkspreed.com
  - name: QRMe
    url: https://qrme.linkspreed.com
  - name: Quexy
    url: https://quexy.linkspreed.com
  - name: Rank
    url: https://rank.linkspreed.com
  - name: RealPin
    url: https://realpin.linkspreed.com
  - name: Reply
    url: https://reply.linkspreed.com
  - name: SeedSpreed
    url: https://seedspreed.linkspreed.com
  - name: Share
    url: https://share.linkspreed.com
  - name: ShareNode
    url: https://sharenode.linkspreed.com
  - name: Shortcut
    url: https://shortcut.linkspreed.com
  - name: Shortrack
    url: https://shortrack.linkspreed.com
  - name: Showit
    url: https://showit.linkspreed.com
  - name: SiteSpace
    url: https://sitespace.linkspreed.com
  - name: Slinky
    url: https://slinky.linkspreed.com
  - name: Slurch
    url: https://slurch.linkspreed.com
  - name: SmartPix
    url: https://smartpix.linkspreed.com
  - name: SnapLink
    url: https://snaplink.linkspreed.com
  - name: Snippite
    url: https://snippite.linkspreed.com
  - name: Snoogie
    url: https://snoogie.linkspreed.com
  - name: SoundChest
    url: https://soundchest.linkspreed.com
  - name: Spypy
    url: https://spypy.linkspreed.com
  - name: Start2Up
    url: https://start2up.linkspreed.com
  - name: Stix
    url: https://stix.linkspreed.com
  - name: Store4Ju
    url: https://store4ju.linkspreed.com
  - name: Storee
    url: https://storee.linkspreed.com
  - name: Storpad
    url: https://storpad.linkspreed.com
  - name: StreamValley
    url: https://streamvalley.linkspreed.com
  - name: StreamValley API
    url: https://api.streamvalley.cf 
  - name: Tacuu
    url: https://tacuu.linkspreed.com
  - name: Takestore
    url: https://takestore.linkspreed.com
  - name: Tasksboard
    url: https://tasksboard.linkspreed.com
  - name: Taya
    url: https://taya.linkspreed.com
  - name: Teamix
    url: https://teamix.linkspreed.com
  - name: Teamslite
    url: https://teamslite.linkspreed.com
  - name: TeamSpreed
    url: https://teamspreed.linkspreed.com
  - name: Teamy
    url: https://teamy.linkspreed.com
  - name: Textpad
    url: https://textpad.linkspreed.com
  - name: Tizza
    url: https://tizza.linkspreed.com
  - name: Toolbox
    url: https://toolbox.linkspreed.com
  - name: Toolkit
    url: https://toolkit.linkspreed.com
  - name: Tuit
    url: https://tuit.cf
  - name: Tungolino
    url: https://tungolino.tk
  - name: Tweetch
    url: https://tweetch.cf 
  - name: Twig
    url: https://twig.cf
  - name: uCube
    url: https://ucube.cf
  - name: UltiCloud
    url: https://ulticloud.tk
  - name: Up2Date
    url: https://up2date.tk
  - name: UpDown
    url: https://updown.ml
  - name: UpNode
    url: https://upnode.cf
  - name: VoiceClub
    url: https://voiceclub.tk
  - name: Web5
    url: https://web5.cf
  - name: Whatsline
    url: https://whatsline.tk
  - name: Workspreed
    url: https://workspreed.tk
  - name: Wrap
    url: https://wrap.gq
  - name: Write
    url: https://write.cf
  - name: Yourpod
    url: https://yourpod.cf
  - name: Zlit
    url: https://zlit.tk

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.linkspreed.com
  # baseUrl: /linkspreed_uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Linkspreed Status
  introTitle: "**Linkspreed Status** is the open-source uptime monitor and status page, powered entirely by Linkspreed."
  introMessage: Get **real-time** data from our [GitHub repository](https://github.com/linkspreed/linkspreed_uptime). Visit Linkspreed now on Github.. [**Jump to Github**](https://github.com/linkspreed)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
